<?php

define('PDF_DEFAULT_FONT', 'helvetica');
define('PDF_DEFAULT_FONT_SIZE', 8);
define('PDF_DEFAULT_FONT_SIZE_HEAD', 9);
define('PDF_DEFAULT_FONT_SIZE_MATRICULATION', 7);

define('PDF_TOPLEFT_SYMBOL_X', 10);
define('PDF_TOPLEFT_SYMBOL_Y', 10);
define('PDF_TOPLEFT_SYMBOL_W', 2.5);

define('PDF_BOTTOMLEFT_SYMBOL_X', PDF_TOPLEFT_SYMBOL_X);
define('PDF_BOTTOMLEFT_SYMBOL_Y', -10);
define('PDF_BOTTOMLEFT_SYMBOL_W', PDF_TOPLEFT_SYMBOL_W);

define('PDF_BOTTOMRIGHT_QR_W', 30);
define('PDF_BOTTOMRIGHT_QR_MARGIN_X', 5);
define('PDF_BOTTOMRIGHT_QR_MARGIN_Y', 5);

define('PDF_ANSWERCIRCLE_W', 5);
define('PDF_ANSWERBOX_W', 2.5);
define('PDF_ANSWERBOX_H', 2.5);

define('PDF_CHECKBOX_MARGIN', 0.5);

define('PDF_CELL_MARGIN', 5);

define('DRAWRULE_MAXTRIES', 1000);
define('DRAWRULE_MAXTIME', 10);